name: Build and Push Staging Image

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  TARGET: stage

jobs:
  build-push-image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.GCP_AR_REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ vars.GCP_AR_REGISTRY }}/${{ vars.GCP_PROJECT }}/${{ vars.GCP_AR_REPO }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
            ${{ vars.GCP_AR_REGISTRY }}/${{ vars.GCP_PROJECT }}/${{ vars.GCP_AR_REPO }}/${{ vars.IMAGE_NAME }}:${{ env.TARGET }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ vars.GCP_SERVICE_ACCOUNT }}
          region: ${{ vars.GCP_REGION }}
          image: ${{ vars.GCP_AR_REGISTRY }}/${{ vars.GCP_PROJECT }}/${{ vars.GCP_AR_REPO }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

